# Generated by Django 4.1.4 on 2023-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacansies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('conditions', models.CharField(max_length=255)),
            ],
        ),
    ]
